### ISSUE TITLE
libopd does not build under Windows

### ISSUE THREAD

**Issue by ilzxc** [CNMAT/CNMAT-odot#255]
`Carbon.h` include is a Mac-specific thing that prevents libopd from building under Windows.

**Comment by maccallum** [comment]
What's the status of this @ilzxc ?

**Comment by ilzxc** [comment]
We don't have a Windows makefile for this, so still open.

**Comment by elsueno** [comment]
I'd also love to be able to use odot in PD on Windows...

Thanks!

**Comment by adrianfreed** [comment]
me too!
I just switched to Windows 10

**Comment by equilet** [comment]
maybe @ramagottfried can take a look, in case this is interesting to him at all...

**Comment by ramagottfried** [comment]
spent a little time on this today, but getting stuck with pd's build system. libo and libopd are building fine in mingw, but in order to build odot for pd we need to link against pd.lib which gets made when you compile pd, and so far none of the build instructions are working for me. 

I *almost* have it building using the suggested automake tools, but get a libtool error about unrecognized characters in one of the "extra" objects bundled with pd (bob~). pd.exe gets compiled, but it fails before making pd.lib.

if anyone is interested in this, and wants to figure out a repeatable process of building pd on windows that'd be great! as far as I can tell, once that's working it shouldn't be too hard to get odot compiling for pd-windows.

(miller's msvc makefile fails looking for pthread which is kind of surprising, it makes me think he's probably cross compiling... if I have more time to look at it I can maybe think about this)

**Comment by maccallum** [comment]
libopd builds on windows
