### ISSUE TITLE
documenting comma in o.expr.codebox, supporting semicolon

### ISSUE THREAD

**Issue by mzed** [CNMAT/CNMAT-odot#347]
It took me a while to figure out that I could put multiple expressions in o.expr.codebox by separating them with a comma. I tried to use ```;```, which fit with my C mentality. Also, ```;``` is the end of line character in gen codebox. The conditional operators tab of the helpfile does have examples with commas, but they aren't obvious.  

Feature request: support ```;```

Documentation request: document the expression separator in a more obvious place.

**Comment by maccallum** [comment]
Sorry about that, but glad you found the comma thing. It should definitely be added to the documentation.

In an earlier version of the language, the semicolon was the expression terminator, but we removed it because of the direction things were heading with the language—a direction that we didn’t have time to explore fully. The idea is that you can think of o.expr.codebox as a bundle that contains a single address: /expr : [<expr1>, <expr2>, …], and that the object maps eval() onto that list. This has some interesting implications for dynamic programming, but again, they haven’t been fully explored.
