### ISSUE TITLE
o.io.slipserial

### ISSUE THREAD

**Issue by wagne342** [CNMAT/CNMAT-odot#381]
I'm having a devil of a time finding o.io.slipserial.maxpat.  Does it still exist somewhere?

**Comment by adrianfreed** [comment]
It doesn’t appear to be where I left it in the repo, but there is a z_o.io.support folder kicking around from 2016 that has it.

**Comment by equilet** [comment]
It's included in a few places now:

1. Music and Computing lib
1. CNMAT o.io lib (experimental folder)
1. various personal projects

**Comment by equilet** [comment]
@wagne342 if you're satisfied w/ these locs, please feel free to close.  Or, if I should put it somewhere that makes more sense for your use case, I can do that too.  Technically the place it "should live" is in 1/2 because the MC lib depends on it and o.io is mothballed.  We don't have a separately active repo for o.io things that we don't use as much.

**Comment by equilet** [comment]
I'm closing this for now, but if there's something else I need to do, feel free to open back up.

**Comment by erra12** [comment]
Can somebody post the link to get the o.io. library - i just cant find it. 
Why isn't it included in the ODOT, OSCuino or OSC master download?

**Comment by equilet** [comment]
Hi @erra12 - the slip serial abstraction offers slip encoding/decoding specifically.  If you have further questions feel free to get in touch at jlubow [at] berkeley [dot] edu - thanks!
