### ISSUE TITLE
Odot 136 doesn't work with max861

### ISSUE THREAD

**Issue by jzarpud** [CNMAT/CNMAT-odot#440]
Odot 136 doesn't seem to work with Max 861 ?

**Comment by maccallum** [comment]
@jzarpud, I'm not able to reproduce that with my system--can you please do the following:

1.  Close all Max windows and quit Max
2. Launch Max and instantiate an odot object
3. Copy and paste here the odot version number and copyright info that gets printed to the Max window
4. Go under the Max menu, choose About Max..., and then click "Copy support information to clipboard" and paste that info here
5. Tell me what OS you're running
6. Tell me how you got odot--either from GitHub, or via the Max Package Manager.

**Comment by jzarpud** [comment]
Hi thank for the quick answer see below
All the best
Jérôme Dupraz

21 rue neuves des boulets 
75011 Paris
France

NB : It works great with Max 8.5.7 and dot 1.3.4 and 1.3.6

> Le 25 févr. 2024 à 16:50, John MacCallum ***@***.***> a écrit :
> 
> 
> @jzarpud <https://github.com/jzarpud>, I'm not able to reproduce that with my system--can you please do the following:
> 
> Close all Max windows and quit Max
> Launch Max and instantiate an odot object
I still have the message :o.route: cannot be loaded due to system security policy

 
> Copy and paste here the odot version number and copyright info that gets printed to the Max window
odot version 1.3.6-0-g9c3aa97 (compiled Sat Jan 20 16:23:10 PST 2024)
by John MacCallum, Adrian Freed, Rama Gottfried, Ilya Rostovtsev
Copyright (c) 2008-21 Regents of the University of California. All rights reserved.

> Go under the Max menu, choose About Max..., and then click "Copy support information to clipboard" and paste that info here
{
	"version" : "Version 8.6.1 (b9925cf828e) (x64 mac)",
	"platform" : "mac",
	"arch" : "x64",
	"osversion" : "Mac OS X Version 12.7.3 (Build 21H1015) x86_64",
	"samplerate" : 44100,
	"iovs" : 512,
	"sigvs" : 64,
	"scheduler_in_audio_interrupt" : "off",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "permanent full",
	"machine_id" : "4af2c1e38ef9854789e0f9ebb4ca9763",
	"eventinterval" : 2,
	"schedinterval" : 1.0,
	"overdrive" : "off",
	"pollthrottle" : 40,
	"queuethrottle" : 100,
	"sysqelemthrottle" : 1000,
	"refreshrate" : 30.0,
	"schedslop" : 25.0,
	"eventprobing" : 1,
	"mixerparallel" : "off",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "viddll",
	"gfxengine" : "glcore",
	"packages" : 	{
		"BEAP" : "1.0.4",
		"CNMAT Externals" : "1.0.5",
		"cv.jit" : "2.0.2",
		"gl3" : "0.3.3",
		"hap" : "1.0.6",
		"jasch objects" : "0.8.3",
		"jit.mo" : "1.1.6",
		"Jitter Tools" : "1.0.10",
		"Max for Live" : "1.0.9",
		"Max for the Visual Arts" : "2.55.3",
		"max-mxj" : "8.2.0",
		"maxforlive-elements" : "1.0.10",
		"Mira" : "1.2.1",
		"Node for Max" : "2.1.3",
		"odot" : "1.3.6",
		"RNBO" : "1.2.4",
		"Sadam Library" : "23.2.7",
		"Syphon" : "1.0.9",
		"VIDDLL" : "1.2.8",
		"Vizzie" : "2.2.2"
	}

}

> Tell me what OS you're running
Mac OS monterey 12.7.3
> Tell me how you got odot--either from GitHub, or via the Max Package Manager.
From Max package

**Comment by maccallum** [comment]
Ah ok, it's due to this quarantine issue. That is supposed to be taken care of when you download it from the package manager, but it looks like it didn't work for you for some reason. I'll look into that tomorrow and get back to you.

In the meantime, using the terminal, type the following command (don't hit return): 

sudo xattr -cr

make sure there's a space after the last 'r'. Then, in the finder, find the odot folder that the Max Package Manager installed (should be in ~/Documents/Max 8/Packages), and drag it onto the terminal window and let go--it'll fill in the path. Again, make sure there's a space between the end of the command you typed, and the beginning of the path to the odot folder. Hit return, and it'll ask you to type your password--this is the password you use to log into your machine--as you type, it won't display anything. Hit return after typing in your password, and hopefully you should be good to go. Make sure to quit Max and reopen.

For reference:

https://apple.stackexchange.com/questions/373176/disable-the-use-of-the-com-apple-quarantine-extended-attribute-on-mojave

**Comment by jzarpud** [comment]
Hi I did what you say but it doesn’t change anything it still tell me : o.collect: unable to load object bundle executable
Thanks

Jérôme

**Comment by maccallum** [comment]
But that's a different error, no? Is it possible that you have two different versions of the odot package on your machine? Can you do a search for o.collect.mxo using spotlight and see if perhaps a couple of versions around?

**Comment by jzarpud** [comment]
Hi John, I actually had a file with a few odot in it that I had made for export, I have supressed them and it seems to work now.
Thank you very much for your answers and for updating the odot family.
All the best

Jérôme
